apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi # Specify the size of the volume
  accessModes:
    - ReadWriteOnce # Specify the access mode
  hostPath: # This is for local development; change it for production
    path: /mnt/data # Path on the host machine
